### ISSUE TITLE
Memory leak when performing inner loop on a copy

### ISSUE THREAD

**Issue by eric-mitchell** [facebookresearch/higher#6]
When running the following script, memory usage seems to continually increase (not all iterations, but many of them in the beginning). Explicitly decrementing the reference counts for the functional model/differentiable optimizer seems to help, but not completely fix the issue. Script for reproducing attached. Monitoring GPU memory usage with `watch -n 0.1 nvidia-smi`. Running PyTorch version 1.3.0, torchvision 0.4.1, higher version 0.1.3@59537fa. Let me know if any other information would be helpful.

Code to reproduce the issue:

```
import torch, torchvision
import higher
import time
from copy import deepcopy


print(torch.__version__, torchvision.__version__)

inner_loop_copy = True # Setting this to False gives no memory usage increase

device = torch.device('cuda:0')
model = torchvision.models.resnet18().to(device)
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

for idx in range(100):
    print(idx)
    if inner_loop_copy:
        model_ = deepcopy(model)
        opt_ = torch.optim.SGD(model_.parameters(), lr=1e-5)
    else:
        model_ = model
        opt_ = opt

    with higher.innerloop_ctx(model_, opt_) as (fm, do):
        pass

    # del fm, do # Uncommenting this helps, but doesn't completely eliminate the memory usage increase
```

**Comment by egrefen** [comment]
Thanks for the minimal repro example, @eric-mitchell! 

We have had some issues with memory which I thought I had successfully dealt with, but this looks unrelated to the fixes I had committed. I'll try to find someone internally who has knowledge of how to debug these memory issues...

**Comment by egrefen** [comment]
Hello @eric-mitchell, just to give you a timeline for looking into this: because of leave and existing commitment of our research engineers who could assist me, we will probably only start to look into this at the beginning of December (unless we receive external contributions, of course).

Sorry I can't do a quick fix, but I'm personally not very well versed in how to debug reference counting/memory leak issues in python (and doubly so when it comes to CUDA memory issues).

**Comment by eric-mitchell** [comment]
Got it. Not sure I will be able to devote much time to it either. For the moment, though, it seems to be at least partially alleviated by explicitly deleting the functional model/differentiable optimizer.

**Comment by raulpuric** [comment]
Jumping on this to say I'm seeing the same thing.

Not sure why but sometimes the code makes it through all of training, sometimes it makes it through only the first 100 metabatches.

For reference, memory usage increases with every single call to innerloop_ctx, and will randomly free memory after several iterations. This results in a saw tooth memory usage pattern that may cause overflows if one is unlucky and all the stars align. I've been detaching and deleting everything I can to no avail.

**Comment by raulpuric** [comment]
Here's a helper function I have to track usage:
```
def report_memory(name=''):
    """Simple GPU memory report."""

    mega_bytes = 1024.0 * 1024.0
    string = name + ' memory (MB)'
    string += ' | allocated: {}'.format(
        torch.cuda.memory_allocated() / mega_bytes)
    string += ' | max allocated: {}'.format(
        torch.cuda.max_memory_allocated() / mega_bytes)
    string += ' | cached: {}'.format(torch.cuda.memory_cached() / mega_bytes)
    string += ' | max cached: {}'.format(
        torch.cuda.max_memory_cached()/ mega_bytes)
    print(string)
```

**Comment by nooralahzadeh** [comment]
Hi, 
Any temporary solution for that? which object we should delete and make cache empty?
Thanks

**Comment by egrefen** [comment]
We're looking into this now.

Here's my version of @eric-mitchell's repro with the helper function from @raulpuric (thanks!).

```python
import torch
import torchvision
import higher
import time
from copy import deepcopy

def report_memory(name=''):
    """Simple GPU memory report."""

    mega_bytes = 1024.0 * 1024.0
    string = name + ' memory (MB)'
    string += ' | allocated: {}'.format(
        torch.cuda.memory_allocated() / mega_bytes)
    string += ' | max allocated: {}'.format(
        torch.cuda.max_memory_allocated() / mega_bytes)
    string += ' | cached: {}'.format(torch.cuda.memory_cached() / mega_bytes)
    string += ' | max cached: {}'.format(
        torch.cuda.max_memory_cached()/ mega_bytes)
    print(string)

print(torch.__version__, torchvision.__version__)

inner_loop_copy = True # Setting this to False gives no memory usage increase

device = torch.device('cuda:0')
model = torchvision.models.resnet18().to(device)
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

for idx in range(100):
    if inner_loop_copy:
        model_ = deepcopy(model)
        opt_ = torch.optim.SGD(model_.parameters(), lr=1e-5)
    else:
        model_ = model
        opt_ = opt

    with higher.innerloop_ctx(model_, opt_) as (fm, do):
        pass
    
    report_memory("idx {}".format(idx))

    # del fm, do # Uncommenting this helps, but doesn't completely eliminate the memory
```

I note that when running it with `inner_loop_copy = False`, or when the lines using `higher.innerloop_ctx` are commented out, the memory usage stays stable around 90Mb allocated, and it unboundedly grows when `inner_loop_copy = True`.

It seems like some stray references to either the optimizer state or patched module are being kept around, preventing their deallocation...

**Comment by egrefen** [comment]
I note it also happens if I replace

```python
with higher.innerloop_ctx(model_, opt_) as (fm, do):
    pass
```

with 

```python
fm = higher.monkeypatch(model_)
```

So my guess the problem is in that function...

**Comment by egrefen** [comment]
Fixed in #15 (we believe). Please let us know if you have ongoing issues.

**Comment by nooralahzadeh** [comment]
I am using the last version of higher 0.1.5, however still have a problem with memory leak:
```ruby
with higher.innerloop_ctx(model, inner_opt, copy_initial_weights=False) as (fast_model, diffopt):
          for step, batch in enumerate(epoch_iterator):
                    report_memory()
                    print("-------------")
                    fast_model.train()
                    outputs = fast_model(batch)
                    loss = outputs[0]  
                    diffopt.step(loss)
```

> memory (MB) | allocated: 678.73095703125 | max allocated: 678.73095703125 | cached: 734.0 | max cached: 734.0
> memory (MB) | allocated: 1357.4619140625 | max allocated: 2036.19287109375 | cached: 2158.0 | max cached: 2158.0
> memory (MB) | allocated: 12340.314453125 | max allocated: 13059.771484375 | cached: 13208.0 | max cached: 13208.0
> memory (MB) | allocated: 23322.634765625 | max allocated: 24041.8564453125 | cached: 24190.0 | max cached: 24190.0
